[package]
name = "backend"
version = "0.1.0"
authors = ["Cheng <machengiam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.13"
dirs = "3.0"
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"]}
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "sqlite" ] }

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]