[package]
name = "oasis"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3"
log = "0.4"
dirs = "3.0"
anyhow = "1.0"
dotenv = "0.15.0"
env_logger = "0.8.3"
tokio = { version = "1.5", features = ["full"] }
serde = { version = "1.0", features = ["derive"]}
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "sqlite" ] }