[package]
name = "oasis"
version = "0.1.0"
authors = ["Cheng <machengiam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.13"
bcrypt = "0.10"
chrono = "0.4"
dirs = "3.0"
dotenv = "0.15.0"
jsonwebtoken = "7"
rand = "0.8"
serde = { version = "1.0", features = ["derive"]}
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "sqlite" ] }
time = "0.2.11"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]